name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      CONNECTION_STRING: "Server=localhost,1433;Database=EnterpriseProjectDB;User Id=sa;Password=Group7Project;MultipleActiveResultSets=true;TrustServerCertificate=true"
      ASPNETCORE_URLS: http://localhost:7125

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Group7Project"
        options: --health-cmd "SELECT 1" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pytest

      - name: Wait for SQL Server to be ready
        run: |
          n=0
          until [ $n -ge 5 ]; do
            nc -z localhost 1433 && break
            n=$((n+1))
            sleep 10
          done
          if [ $n -ge 5 ]; then
            echo "Timeout waiting for SQL Server to start"
            exit 1
          fi
          echo "SQL Server is ready"

      - name: Restore
        run: dotnet restore ./AI_Summarize_Quiz_Web.sln

      - name: Build
        run: dotnet build ./AI_Summarize_Quiz_Web.sln --configuration Release --no-restore

      - name: Set Connection String
        run: echo "ConnectionStrings:EnterpriseProjectDB=$CONNECTION_STRING" >> ./AI_Summarize_Quiz_Web/appsettings.json

      - name: Start server
        run: dotnet run --project ./AI_Summarize_Quiz_Web

      - name: Run Pytest
        run: |
          cd AutomatedTestingAPI
          pytest AutomatedTestingAPI.py
